### ISSUE TITLE
Channel.trigger-typing crashes with "411 Length required"

### ISSUE THREAD

**Issue by throwaway-30964** [shuppet/p6-api-discord#17]
``` 
  whenever $discord.events -> $event {
    if $event<t> eq 'TYPING_START' {
      my $channel = await $discord.get-channel($event<d><channel_id>);
      await $channel.trigger-typing;
    }
  }
```

Crashes with:

```
Died because of the exception:
    An operation first awaited:
      [...]                                                                     

    Died with the exception:
        Server responded with 411 Length Required
          in block  at [...]/BD9BD084131C6E7D2BF4FE09570E5EBE604DB8FA (Cro::HTTP::Client) line 410    
```

The problem seems to be that the request doesn't contain a Content-Length header:

> The HyperText Transfer Protocol (HTTP) 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.

**Comment by throwaway-30964** [comment]
The fix is trivial, just add an empty body here https://github.com/shuppet/p6-api-discord/blob/master/lib/API/Discord/Channel.pm6#L135

```
$.api.rest.post(endpoint-for(self, 'trigger-typing'), :body(''));
```

**Comment by kawaii** [comment]
Thanks for the report and provided patch!
